[package]
name = "lib-time"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]

[lints]
workspace = true
