[package]
workspace = "../../workspace-common"
name = "lib-time"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
web-time.workspace = true

[lints]
workspace = true
