[package]
name = "application-robot"
description = "A simple robot moving across a 2D-plane."
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
engine-robot.workspace = true
gam3du-framework-common.workspace = true
gam3du-framework.workspace = true
runtime-python.workspace = true

tokio = { workspace = true, features = ["rt", "signal", "macros", "time"] }
tokio-util = { workspace = true }
rustpython-vm.workspace = true
log.workspace = true
serde_json.workspace = true
winit = { workspace = true, default-features = true }

[build-dependencies]
gam3du-framework-common.workspace = true
runtime-python-bindgen.workspace = true

serde_json.workspace = true

[lints]
workspace = true
