[package]
workspace = "../../workspace-common"
name = "lib-geometry"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
readme.workspace = true

[dependencies]
glam = { workspace = true, features = ["std"] }

[lints]
workspace = true
